#pragma once

// Firmware identity
#define AI_PET_FIRMWARE_VERSION "0.1.0-xiao-bringup"

// Feature gates
#define AI_PET_ENABLE_PLAYBACK 1
#define AI_PET_ALLOW_INSECURE_HTTPS 0

// Serial and pairing portal
#define AI_PET_SERIAL_BAUD 115200
#define AI_PET_PAIRING_AP_PASSWORD "petsetup"

// Board defaults
#define AI_PET_DEFAULT_DEVICE_ID "xiao-esp32s3-sense"
#define AI_PET_DEFAULT_LOCALE "zh-CN"
#define AI_PET_DEFAULT_CLOUD_BASE_URL "http://192.168.8.95:8000"

// Audio capture
#define AI_PET_AUDIO_SAMPLE_RATE_HZ 16000
// Fixed-window fallback baseline kept for safe rollback and no-speech fallback.
#define AI_PET_AUDIO_CAPTURE_MS 1500
#define AI_PET_AUDIO_CAPTURE_STALL_TIMEOUT_MS 5000
#define AI_PET_AUDIO_BITS_PER_SAMPLE 16
#define AI_PET_AUDIO_CHANNELS 1
#define AI_PET_PDM_DATA_PIN 41
#define AI_PET_PDM_CLOCK_PIN 42

// MAX98357 playback
#define AI_PET_PLAYBACK_DEFAULT_SAMPLE_RATE_HZ 24000
#define AI_PET_PLAYBACK_BITS_PER_SAMPLE 16
#define AI_PET_PLAYBACK_CHANNELS 2
#define AI_PET_MAX98357_BCLK_PIN 7
#define AI_PET_MAX98357_LRCLK_PIN 8
#define AI_PET_MAX98357_DIN_PIN 9
#define AI_PET_PLAYBACK_I2S_WRITE_CHUNK_BYTES 2048

// Lightweight VAD MVP
#define AI_PET_ENABLE_LIGHTWEIGHT_VAD 1
#define AI_PET_VAD_FRAME_MS 20
#define AI_PET_VAD_BOOTSTRAP_MS 60
#define AI_PET_VAD_PREROLL_MS 300
#define AI_PET_VAD_MIN_CAPTURE_MS 640
#define AI_PET_VAD_MAX_CAPTURE_MS 6000
#define AI_PET_VAD_END_SILENCE_MS 460
#define AI_PET_VAD_END_CONFIRM_MS 100
#define AI_PET_VAD_START_TRIGGER_FRAMES 2
#define AI_PET_VAD_START_RATIO_NUM 5
#define AI_PET_VAD_START_RATIO_DEN 4
#define AI_PET_VAD_START_OFFSET_ABS 6
#define AI_PET_VAD_START_FLOOR_ABS 64
#define AI_PET_VAD_END_RATIO_NUM 3
#define AI_PET_VAD_END_RATIO_DEN 2
#define AI_PET_VAD_END_OFFSET_ABS 12
#define AI_PET_VAD_END_FLOOR_ABS 45
#define AI_PET_VAD_RESUME_TRIGGER_FRAMES 4
#define AI_PET_VAD_RESUME_OFFSET_ABS 24
#define AI_PET_VAD_NEAR_MAX_END_SILENCE_MS 260
#define AI_PET_VAD_NEAR_MAX_WINDOW_MS 300
#define AI_PET_VAD_POST_SPEECH_MAX_MS 1400
#define AI_PET_VAD_POST_SPEECH_GUARD_MIN_SILENCE_MS 240

// Wi-Fi and cloud retry behavior
#define AI_PET_WIFI_CONNECT_TIMEOUT_MS 20000
#define AI_PET_WIFI_RETRY_INTERVAL_MS 10000
#define AI_PET_CLOUD_CONNECT_TIMEOUT_MS 5000
#define AI_PET_HTTP_TIMEOUT_MS 20000

// PDM DMA tuning
#define AI_PET_I2S_DMA_BUFFER_COUNT 8
#define AI_PET_I2S_DMA_BUFFER_LENGTH 512
#define AI_PET_I2S_READ_CHUNK_BYTES 2048
